### ISSUE TITLE
Tuple.reduce with ellipses raises on the last invalid index

### ISSUE THREAD

**Issue by asmeurer** [Quansight-Labs/ndindex#167]
For example:

```py
>>> Tuple(..., 0, 0).reduce((0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/ndindex/ndindex/tuple.py", line 367, in reduce
    s = s.reduce(shape, axis=axis, negative_int=negative_int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/ndindex/ndindex/integer.py", line 100, in reduce
    self._raise_indexerror(shape, axis)
  File "/Users/aaronmeurer/Documents/ndindex/ndindex/integer.py", line 63, in _raise_indexerror
    raise IndexError(f"index {self.raw} is out of bounds for axis {axis} with size {size}")
IndexError: index 0 is out of bounds for axis 1 with size 0
```

vs.

```
>>> np.empty((0, 0))[..., 0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 0 is out of bounds for axis 0 with size 0
```

This means we have to set `same_exception=False` all over the tests.

It's because of the reverse loop https://github.com/Quansight-Labs/ndindex/blob/bdb7edbc944230c462f60af98401d436f7c64960/ndindex/tuple.py#L337

**Comment by asmeurer** [comment]
Maybe we could raise them all together with an [exception group](https://docs.python.org/3/library/exceptions.html#ExceptionGroup). Not sure if it's a good idea, though.
